### PR TITLE
[backend] Game logic

### PR DESCRIPTION
**Pull request by falkecarlsen**

### CODE REVIEW

**Comment by NicEastvillage** [comment]
When are we merging this?

**Comment by falkecarlsen** [comment]
Soon<sup>TM</sup>
But really, I think when backend is finished to a minimum viable state, this should be merged. This allows parallel work on middleware/frontend while any part is polished further.

**Comment by NicEastvillage** [comment]
Yeah, I agree. I think we should do it now or implement `Game::performPlayCard` (to some extent) and then do it. But `master`'s Actions uses indexes instead of Spell and Creature, so we have to integrate that as a minimum.

**Comment by NicEastvillage** [comment]
Let's merge this so we can start playing with the project again.

**Pull request merged**
